import asyncio
import io
import zipfile
import uuid
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse

from models.schemas import TaskRequest, AgentEvent
from orchestrator import Orchestrator
from database import save_task, get_task_history, get_task_result, get_db
from config import settings, MODEL_PRICING, get_model_pricing
from api.websocket import manager

router = APIRouter()
orchestrator = Orchestrator()


# Store running tasks and their results.
# task_results is capped at _TASK_CACHE_MAX entries (oldest evicted first) so
# the process memory stays bounded on long-running deployments.
running_tasks: dict[str, asyncio.Task] = {}
task_results: dict[str, dict] = {}
_TASK_CACHE_MAX = 200


def _evict_oldest_results():
    """Drop the oldest entry once the cache exceeds its limit."""
    while len(task_results) > _TASK_CACHE_MAX:
        task_results.pop(next(iter(task_results)))


@router.post("/task")
async def create_task(request: TaskRequest):
    """Create a new coding task and start agent execution."""
    # Input validation
    if not request.description.strip():
        return {"error": "Task description cannot be empty"}
    if len(request.description) > 2000:
        return {"error": "Task description too long (max 2000 chars)"}

    # Validate model selection (fall back to default if unknown)
    model = request.model or settings.OPENAI_MODEL
    if model not in settings.AVAILABLE_MODELS:
        return {"error": f"Unsupported model '{model}'. Choose from {settings.AVAILABLE_MODELS}"}

    budget_cap = request.budget_cap_usd if request.budget_cap_usd is not None else settings.BUDGET_CAP_USD

    task_id = str(uuid.uuid4())[:8]

    async def event_callback(event: AgentEvent):
        await manager.send_event(task_id, event)

    async def run_task():
        result = await orchestrator.execute_task(
            request.description, request.language, event_callback,
            task_id=task_id, model=model, budget_cap_usd=budget_cap,
        )

        task_results[task_id] = result
        _evict_oldest_results()

        # Save to history
        save_task(
            task_id, request.description, result["status"],
            request.language, result
        )

        # Cleanup running task reference
        running_tasks.pop(task_id, None)

        return result

    # Run task in background
    task = asyncio.create_task(run_task())
    running_tasks[task_id] = task

    return {"task_id": task_id, "status": "started", "description": request.description}


@router.get("/task/{task_id}")
async def get_task(task_id: str):
    """Get the current status and results of a task."""
    # Check completed results cache
    if task_id in task_results:
        return task_results[task_id]

    # Check if task is still running
    if task_id in running_tasks:
        task = running_tasks[task_id]
        if task.done():
            try:
                result = task.result()
                task_results[task_id] = result
                return result
            except Exception as e:
                return {"task_id": task_id, "status": "failed", "error": str(e)}
        return {"task_id": task_id, "status": "in_progress"}

    # Check database
    db_result = get_task_result(task_id)
    if db_result:
        return db_result

    return {"task_id": task_id, "status": "not_found"}


@router.post("/task/{task_id}/cancel")
async def cancel_task(task_id: str):
    """Cancel a running task."""
    if task_id in running_tasks:
        task = running_tasks[task_id]
        if not task.done():
            task.cancel()
            running_tasks.pop(task_id, None)
            return {"task_id": task_id, "status": "cancelled"}
    return {"task_id": task_id, "status": "not_found"}


@router.get("/task/{task_id}/download")
async def download_task_code(task_id: str):
    """Download all generated code as a ZIP file."""
    result = task_results.get(task_id) or get_task_result(task_id)

    if not result or result.get("status") != "completed":
        return {"error": "Task not found or not completed"}

    data = result.get("data", {})
    code_files = data.get("code_files", [])

    if not code_files:
        return {"error": "No code files generated"}

    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in code_files:
            zf.writestr(file["path"], file["content"])

        # Add a README
        readme = f"# Generated by AI Software Engineer\n\n"
        readme += f"**Task:** {data.get('task_description', 'N/A')}\n\n"
        readme += f"## Files\n"
        for file in code_files:
            readme += f"- `{file['path']}` ({file['language']})\n"
        readme += f"\n## Metrics\n"
        metrics = data.get("metrics", {})
        readme += f"- Tokens used: {metrics.get('total_tokens', 0)}\n"
        readme += f"- Cost: ${metrics.get('total_cost_usd', 0)}\n"
        readme += f"- Time: {metrics.get('time_taken_seconds', 0)}s\n"
        readme += f"- Review iterations: {metrics.get('review_iterations', 0)}\n"
        zf.writestr("README.md", readme)

    zip_buffer.seek(0)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename=ai-generated-{task_id}.zip"},
    )


@router.get("/models")
async def list_models():
    """List the available LLM models, their pricing, and the current default.
    
    The frontend uses this to populate the model selector and show a rough
    cost-per-1k-tokens estimate for each option.
    """
    models = []
    for name in settings.AVAILABLE_MODELS:
        pricing = get_model_pricing(name)
        models.append({
            "id": name,
            "input_per_1k": pricing["input"],
            "output_per_1k": pricing["output"],
            "is_default": name == settings.OPENAI_MODEL,
        })
    return {
        "models": models,
        "default": settings.OPENAI_MODEL,
        "budget_cap_usd": settings.BUDGET_CAP_USD,
    }


@router.get("/history")
async def get_history():
    """Get task history."""
    history = get_task_history(limit=50)
    return {"history": [h.model_dump() for h in history]}


@router.get("/history/{task_id}")
async def get_history_task(task_id: str):
    """Get a specific task from history."""
    result = get_task_result(task_id)
    if result:
        return result
    return {"error": "Task not found"}


@router.delete("/history/{task_id}")
async def delete_history_task(task_id: str):
    """Delete a task from history."""
    conn = get_db()
    try:
        conn.execute("DELETE FROM task_history WHERE task_id = ?", (task_id,))
        conn.commit()
    finally:
        conn.close()
    return {"status": "deleted"}


@router.websocket("/ws/{task_id}")
async def websocket_endpoint(websocket: WebSocket, task_id: str):
    """WebSocket endpoint for real-time agent updates."""
    await manager.connect(websocket, task_id)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        await manager.disconnect(websocket, task_id)